apiVersion: v1
kind: Service
metadata:
  name: launchpad-service
spec:
  selector:
    app: launchpad
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer  # Change to NodePort if using Minikube

