apiVersion: apps/v1
kind: Deployment
metadata:
  name: launchpad-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: launchpad
  template:
    metadata:
      labels:
        app: launchpad
    spec:
      containers:
        - name: launchpad-container
          image: <your-image-name>  # e.g., aksharrastogi/launchpad-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: ELASTICSEARCH_URL
              value: "http://elasticsearch:9200"

