"""Add vendor_id to products

Revision ID: b4d69bfc382e
Revises: 0b59bced1749
Create Date: 2025-05-14 18:13:23.543852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4d69bfc382e'
down_revision: Union[str, None] = '0b59bced1749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('addresses', sa.Column('street', sa.String(), nullable=False))
    op.drop_index('ix_addresses_uer_id', table_name='addresses')
    op.create_index(op.f('ix_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    op.drop_constraint('addresses_uer_id_fkey', 'addresses', type_='foreignkey')
    op.create_foreign_key(None, 'addresses', 'users', ['user_id'], ['id'])
    op.drop_column('addresses', 'address_line2')
    op.drop_column('addresses', 'uer_id')
    op.drop_column('addresses', 'address_line1')
    op.add_column('products', sa.Column('vendor_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_products_vendor_id'), 'products', ['vendor_id'], unique=False)
    op.create_foreign_key(None, 'products', 'vendors', ['vendor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_vendor_id'), table_name='products')
    op.drop_column('products', 'vendor_id')
    op.add_column('addresses', sa.Column('address_line1', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('addresses', sa.Column('uer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('addresses', sa.Column('address_line2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.create_foreign_key('addresses_uer_id_fkey', 'addresses', 'users', ['uer_id'], ['id'])
    op.drop_index(op.f('ix_addresses_user_id'), table_name='addresses')
    op.create_index('ix_addresses_uer_id', 'addresses', ['uer_id'], unique=False)
    op.drop_column('addresses', 'street')
    op.drop_column('addresses', 'user_id')
    # ### end Alembic commands ###
