# Module: alembic/versions/f9186bf5f0f9_add_category_id_to_products.py
# Brief: TODO - add description

"""add category_id to products

Revision ID: f9186bf5f0f9
Revises: 
Create Date: 2025-05-01 12:07:42.853446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9186bf5f0f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('vendor_id', sa.Integer(), nullable=False))
    op.alter_column('products', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_foreign_key(None, 'products', 'vendors', ['vendor_id'], ['id'])
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.drop_column('products', 'category')
    op.drop_column('products', 'brand')
    op.drop_column('products', 'vendor')
    op.drop_column('wishlist', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('vendor', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.alter_column('products', 'price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('products', 'vendor_id')
    op.drop_column('products', 'category_id')
    # ### end Alembic commands ###
