version: '3.9'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    container_name: elasticsearch1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9201:9201

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.13
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

